import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    "introduction/introduction",
    "introduction/sponsors",
    "introduction/volunteers",
    {
      type: "category",
      label: "Projects",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "projects" }],
    },
    {
      type: "category",
      label: "Git Guide",
      collapsed: true,
      items: [
        { type: "autogenerated", dirName: "git-guide/introduction" },
        {
          type: "category",
          label: "Working Copies",
          collapsed: true,
          items: [
            { type: "autogenerated", dirName: "git-guide/working-copies" },
          ],
        },

        {
          type: "category",
          label: "Setup",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "git-guide/git-workflow/setup",
            },
          ],
        },
        {
          type: "category",
          label: "Stage Changes",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "git-guide/git-workflow/stage-changes",
            },
          ],
        },
        {
          type: "category",
          label: "Repository Update",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "git-guide/git-workflow/finish",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Internships",
      link: {
        type: "generated-index",
      },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Introduction",
          link: {
            type: "doc",
            id: "internships/introduction/about",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "internships/introduction",
            },
          ],
        },
        {
          type: "category",
          label: "GSoC",
          link: {
            type: "doc",
            id: "internships/gsoc/gsoc-introduction",
          },
          collapsed: true,
          items: [
            { type: "autogenerated", dirName: "internships/gsoc" },
            {
              type: "category",
              label: "Previous Years",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "internships/gsoc-previous",
                },
              ],
            },            

          ],
        },

        {
          type: "category",
          label: "GSoD",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "internships/gsod",
            },
          ],
        },

        {
          type: "category",
          label: "Calico",
          link: {
            type: "doc",
            id: "internships/calico/calico-introduction",
          },
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "internships/calico",
            },
          ],
        },

        {
          type: "category",
          label: "Other",
          collapsed: true,
          items: [
            {
              type: "autogenerated",
              dirName: "internships/palisadoes",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
