import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Palisadoes',
      link: {
        type: 'doc',
        id: 'introduction/introduction',
      },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'introduction' }],
    },
    {
      type: 'category',
      label: 'Git Guide',
      link: {
        type: 'doc',
        id: 'git-guide/introduction/quickstart',
      },
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'git-guide/introduction' },
        {
          type: 'category',
          label: 'Working Copies',
          collapsed: true,
          items: [
            { type: 'autogenerated', dirName: 'git-guide/working-copies' },
          ],
        },

        {
          type: 'category',
          label: 'Setup',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'git-guide/git-workflow/setup',
            },
          ],
        },
        {
          type: 'category',
          label: 'Stage Changes',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'git-guide/git-workflow/stage-changes',
            },
          ],
        },
        {
          type: 'category',
          label: 'Repository Update',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'git-guide/git-workflow/finish',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Internships',
      link: {
        type: 'doc',
        id: 'internships/introduction/faq',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Introduction',
          link: {
            type: 'doc',
            id: 'internships/introduction/faq',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'internships/introduction',
            },
          ],
        },
        {
          type: 'category',
          label: 'GSoC',
          link: {
            type: 'doc',
            id: 'internships/gsoc/gsoc-introduction',
          },
          collapsed: true,
          items: [
            { type: 'autogenerated', dirName: 'internships/gsoc' },

            {
              type: 'category',
              label: 'Previous Ideas',
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'internships/gsoc-previous',
                },
              ],
            },
            {
              type: 'category',
              label: 'GSoC Reports',
              collapsed: true,
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'internships/reports/gsoc',
                },
              ],
            },
          ],
        },

        {
          type: 'category',
          label: 'GSoD',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'internships/gsod',
            },
          ],
        },

        {
          type: 'category',
          label: 'Calico',
          link: {
            type: 'doc',
            id: 'internships/calico/calico-introduction',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'internships/calico',
            },
          ],
        },

        {
          type: 'category',
          label: 'Other',
          link: {
            type: 'doc',
            id: 'internships/palisadoes/palisadoes-introduction',
          },
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'internships/palisadoes',
            },
          ],
        },
        {
          type: 'category',
          label: 'Internship Reports',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'internships/reports/other',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
